### ISSUE TITLE
Support for turbolinks 3 or turbolinks 5?

### ISSUE THREAD

**Issue by anothermh** [antpaw/bhf#19]
Turboblinks 2 has been superseded by Turbolinks 3 (https://github.com/turbolinks/turbolinks-classic) which has itself been superseded by Turbolinks 5 (https://github.com/turbolinks/turbolinks). Any chance bhf will be updated to support these? I can't test because my app requires Turbolinks 3 and the bhf is locked to the 2.x series.

**Comment by antpaw** [comment]
https://rubygems.org/gems/turbolinks/ yes as soon as it's out of beta, i looked at the docs and there shouldn't be too many/hard breaking changes, thanks for the notice

**Comment by antpaw** [comment]
bhf now support turbolinks 5 in the newest beta version 1.0.0.beta6
